version: "3"

services:
  nota_ai_dev_env:
    image: dregistry.nota.ai/nota/people/${USER}/nota_ai_dev_env:latest
    environment:
      USERNAME: ${USER}
    build:
      context: .
      args:
        USERNAME: ${USER}
        IMG_URL: ${IMG_URL:-tensorflow/tensorflow:latest}
    volumes:
      - ../:/workspace:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig
      - ~/.ssh:/home/${USERNAME}/.ssh
      - /mnt/nas_new:/mnt/nas_new
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    command: /bin/sh -c "while sleep 1000; do :; done"            
    